lang:
  prefix: "&8[&7B站&8]"
  inputuser: "请输入你的B站用户名来完成绑定"
  inputbvid:
    - "请输入你发布的视频的BV号"
    - "例如:"
  bind: "你已经成功绑定了你的BiliBili账号"
  postcheck:
    success: "你成功发布了一个新视频! 感谢你对服务器的支持"
    getfail: "我们暂时无法查询到你的视频信息,这可能是我们的网络发生了异常,请稍后再试!"
    videofail: "你的视频不符合规范,请查阅规范后重写提交!"
  reward: "你的奖励已发放!"
  unbind: "你成功取消了你的绑定账号"
  nobind: "你还没有绑定你的B站账号"
  announcement: "玩家 %player% 为服务器发布了一条宣传视频!"
  gui:
    title: "%player% 的B站视频宣传"
    board: " "
    skull:
      name: "%player%"
      lore:
        - "&7 "
        - "你好"
    bind:
      name: "绑定B站账号"
      lore:
        - "&7 "
        - "你好"
    rule:
      name:
        name: "如何使用?"
        lore:
          - "&7 "
          - "你好"
    toper:
      name: "发布视频数量排行"