name: BiliBiliToper
version: ${project.version}
api-version: 1.19
main: me.xiaozhangup.bilibilitoper.BiliBiliToper
authors:
  - xiaozhangup

libraries:
  - com.alibaba.fastjson2:fastjson2:2.0.13

commands:
  bilitoper:
    aliases:
      - bili